# .gitlab/secret-detection-ruleset.toml

# Enable secret detection
[secret_detection]
  enabled = true

  # Define rules
  [[secret_detection.rules]]
    # Rule ID
    id = "AWS_SECRET_KEY"
    
    # Pattern to search for
    pattern = "AKIA[0-9A-Z]{16}"

    # Description of the rule
    description = "Potential AWS Secret Key"
    
    # Severity level (optional)
    severity = "high"
    
    # Excludes (optional)
    # exclude = "test/**/*"  # Example exclude pattern
    
  [[secret_detection.rules]]
    id = "GITHUB_TOKEN"
    pattern = "[0-9a-fA-F]{40}"
    description = "Potential GitHub Token"
    severity = "medium"
